import os

env = SConscript("../godot_cpp/SConstruct")
env.Append(CPPPATH=['src'])
dest_dir = "../../src/bin/gozen/"

num_jobs = ARGUMENTS.get('jobs', 16)
platform = ARGUMENTS.get('platform', 'windows')

src = Glob("src/*.cpp")
libpath = '{}libgozen{}{}'.format(dest_dir, env['suffix'], env['SHLIBSUFFIX'])
shardlib = env.SharedLibrary(libpath, src)

Default(shardlib)

